PARAMETERS:
  DEFAULT:
    train_mode: train # train or eval
    epochs: 300
    batch_size: 128
    dataset: mnist
    dataset_dir: data
    input_size: [3, 224, 224]
    image_mean: [0.485, 0.456, 0.406] # image default mean: [0.5, 0.5, 0.5]
    image_std: [0.229, 0.224, 0.225] # image default std: [0.5, 0.5, 0.5]
    image_dtype: float32 # "float32", "float16", or "bfloat16"
    input_img_mode: RGB # "RGB" or "L"
    no_aug: false
    re_prob: 0.0 # Random erase probability
    re_mode: pixel # Random erase mode: "const", "pixel", or "rand"
    re_count: 1 # Random erase count
    re_split: false # Random erase split
    class_map: null
    dataset_download: false
    seed: 42
    repeats: 0.0
    input_key: null
    target_key: null
    dataset_trust_remote_code: false
    use_multi_epochs_loader: false
    pin_memory: true
    device_type: cuda # "cuda" or "cpu"
    workers: 4
  SHARED:
    num_classes: 1000
  train:
    training: true
    split: train
    num_samples: null
    interpolation: bicubic # "random", "bilinear", "bicubic"
    crop_mode: rrc # Training random crop mode: "rrc", "rkrc", "rkrr"
    scale: [0.08, 1.0] # Random resize scale
    ratio: [0.75, 1.3333333333333334] # Random resize aspect ratio
    hflip: 0.5 # Random horizontal flip probability
    vflip: 0.0 # Random vertical flip probability
    color_jitter: 0.4 # Color jitter factor (0 means no jitter)
    color_jitter_prob: null # Color jitter probability
    grayscale_prob: 0.0 # Random grayscale probability
    gaussian_blur_prob: 0.0 # Random Gaussian blur probability
    auto_augment: null # Auto augment policy (e.g., "v0", "original", "v0r", "originalr", "3a", "rand-m9-mstd0.5-inc1", ...)
  eval:
    training: false
    split: validation
    num_samples: null
    interpolation: random # "bilinear", "bicubic"
    crop_pct: 0.875
  mixup:
    mixup_alpha: 0.0
    cutmix_alpha: 0.0
    cutmix_minmax: null # null or [min, max]
    prob: 1.0
    switch_prob: 0.5
    mode: batch # "batch", "pair", or "elem"
    label_smoothing: 0.1
_obj_:
  - _addr_: functools.partial
  - - _call_
    - [_obj_, {_addr_: map}]
    - - _obj_
      - {_addr_: structcast.core.specifier.FlexSpec}
      - {_attr_: model_validate}
      - {_call_: {"image": "0", "label": 1}}
    - - _obj_
      - _addr_: timm.data.create_loader
      - _call_:
          dataset:
            - _obj_
            - _addr_: timm.data.create_dataset
            - _call_:
                _jinja_yaml_: |-
                  name: {{dataset}}
                  root: {{dataset_dir}} 
                  class_map: {{class_map}}
                  download: {{dataset_download}}
                  batch_size: {{batch_size}}
                  seed: {{seed}}
                  repeats: {{repeats}}
                  input_img_mode: {{input_img_mode}}
                  input_key: {{input_key}}
                  target_key: {{target_key}}
                  trust_remote_code: {{dataset_trust_remote_code}}
                  _jinja_group_: {{train_mode}}
                  {% raw %}
                  _jinja_yaml_: |- 
                    is_training: {{training}}
                    split: {{split}}
                    num_samples: {{num_samples}}
                  {% endraw %}
          collate_fn:
            - _obj_
            - _addr_: timm.data.FastCollateMixup
            - _call_:
                _jinja_group_: mixup
                _jinja_yaml_: |-
                  mixup_alpha: {{mixup_alpha}}
                  cutmix_alpha: {{cutmix_alpha}}
                  cutmix_minmax: {{cutmix_minmax}}
                  prob: {{prob}}
                  switch_prob: {{switch_prob}}
                  mode: {{mode}}
                  label_smoothing: {{label_smoothing}}
          _jinja_yaml_: |-
            input_size: {{input_size}}
            use_multi_epochs_loader: {{use_multi_epochs_loader}}
            mean: {{image_mean}}
            std: {{image_std}}
            pin_memory: {{pin_memory}}
            img_dtype: [_obj_, _addr_: "torch.{{image_dtype}}"]
            device: [_obj_, _addr_: torch.device, [_call_, {{device_type}}]]
            distributed: false
            use_prefetcher: true
            batch_size: {{batch_size}}
            num_workers: {{workers}}
            _jinja_group_: {{train_mode}}
            {% if train_mode == "train" %}
            {% raw %}
            _jinja_yaml_: |-
              is_training: {{training}}
              interpolation: {{interpolation}}
              no_aug: {{no_aug}}
              re_prob: {{re_prob}}
              re_mode: {{re_mode}}
              re_count: {{re_count}}
              re_split: {{re_split}}
              train_crop_mode: {{crop_mode}}
              scale: {{scale}}
              ratio: {{ratio}}
              hflip: {{hflip}}
              vflip: {{vflip}}
              color_jitter: {{color_jitter}}
              color_jitter_prob: {{color_jitter_prob}}
              grayscale_prob: {{grayscale_prob}}
              gaussian_blur_prob: {{gaussian_blur_prob}}
              auto_augment: {{auto_augment}}
              num_aug_repeats: 0
              num_aug_splits: 0 # diable due to use_prefetcher
            {% endraw %}
            {% else %}
            {% raw %}
            _jinja_yaml_: |-
              is_training: {{training}}
              interpolation: {{interpolation}}
              crop_pct: {{crop_pct}}
            {% endraw %}
            {% endif %}
