"""StructCast-Model: Construct neural network models and training workflows by structcast package."""

from typing import TYPE_CHECKING

__version__ = "5.0.0"
__all__ = [
    "EVENTS",
    "EVENT_PROTOCOLS",
    "BaseInfo",
    "BaseTrainer",
    "BestCriterion",
    "DataProvider",
    "DatasetLike",
    "Learner",
    "OnBest",
    "OnEpochBegin",
    "OnEpochEnd",
    "OnTrainingBegin",
    "OnTrainingEnd",
    "OnTrainingStepBegin",
    "OnTrainingStepEnd",
    "OnUpdate",
    "OnValidationBegin",
    "OnValidationEnd",
    "OnValidationStepBegin",
    "OnValidationStepEnd",
    "Printer",
    "ProgressBar",
    "SimpleDataProvider",
    "base_trainer",
    "builders",
    "flax",
    "get_dataset",
    "get_dataset_size",
    "keras",
    "loggers",
    "torch",
    "utils",
]

if TYPE_CHECKING:
    from structcast_model import base_trainer, builders, flax, keras, loggers, torch, utils
    from structcast_model.base_trainer import (
        EVENT_PROTOCOLS,
        EVENTS,
        BaseInfo,
        BaseTrainer,
        BestCriterion,
        DataProvider,
        DatasetLike,
        Learner,
        OnBest,
        OnEpochBegin,
        OnEpochEnd,
        OnTrainingBegin,
        OnTrainingEnd,
        OnTrainingStepBegin,
        OnTrainingStepEnd,
        OnUpdate,
        OnValidationBegin,
        OnValidationEnd,
        OnValidationStepBegin,
        OnValidationStepEnd,
        Printer,
        ProgressBar,
        SimpleDataProvider,
        get_dataset,
        get_dataset_size,
    )
else:
    import sys

    from structcast.utils.lazy_import import LazySelectedImporter

    import_structure = {
        "builders": [],
        "flax": [],
        "keras": [],
        "loggers": [],
        "torch": [],
        "utils": [],
        "base_trainer": [
            "EVENTS",
            "EVENT_PROTOCOLS",
            "BaseInfo",
            "BaseTrainer",
            "BestCriterion",
            "DataProvider",
            "DatasetLike",
            "Learner",
            "OnBest",
            "OnEpochBegin",
            "OnEpochEnd",
            "OnTrainingBegin",
            "OnTrainingEnd",
            "OnTrainingStepBegin",
            "OnTrainingStepEnd",
            "OnUpdate",
            "OnValidationBegin",
            "OnValidationEnd",
            "OnValidationStepBegin",
            "OnValidationStepEnd",
            "Printer",
            "ProgressBar",
            "SimpleDataProvider",
            "get_dataset",
            "get_dataset_size",
        ],
    }
    sys.modules[__name__] = LazySelectedImporter(__name__, globals(), import_structure)
